import base from "./base";

export default {
  ...base,
  env: "development",
  maindb: process.env["MONGODB_URI"],
  app1db: process.env["APP1_DB_URI"],
  adminUsername: process.env["ADMIN_USERNAME"],
  adminPassword: process.env["ADMIN_PASSWORD"],
  domainFe: process.env["DOMAIN_FE"],
  googleClientId: process.env["YOUR_CLIENT_ID"],
  googleClientSecret: process.env["YOUR_CLIENT_SECRET"],
  protocol: process.env["PROTOCOL"],
  host: process.env["HOST"],
  smtpHost: process.env['SMTP_HOST'],
  smtpPort: process.env['SMTP_PORT'],
  smtpUser: process.env['SMTP_USER'],
  smtpPassword: process.env['SMTP_PASSWORD'],
  mailerFrom: process.env['MAILER_FROM'],
  adminMail: process.env['ADMIN_MAIL'],
  awsRegion: process.env['AWS_REGION'],
  awsAccessKey: process.env['AWS_ACCESS_KEY'],
  awsSecret: process.env['AWS_SECRET'],
  awsBucketName: process.env['AWS_BUCKET_NAME'],
  awsBucketEndpoint: process.env['AWS_BUCKET_ENDPOINT'],
  awsFolderName: process.env['AWS_FOLDER_NAME'],
  debug: true,
};
