import { SettingTypes } from "../graphql/modules/setting/setting.model";

export enum SettingGroupSlug {
  COMMON = "COMMON",
  BOTANIKA = "BOTANIKA",
}
export enum SettingKey {
  // Cấu hình chung
  TITLE = "TITLE",
  WEBSITE_DOMAIN = "WEBSITE_DOMAIN",
  API_DOMAIN = "API_DOMAIN",
  MEDIA_DOMAIN = "MEDIA_DOMAIN",
  LOGO_URL = "LOGO_URL",
  MAINTENANCE = "MAINTENANCE",

  // cấu hình website
  USE_MENU_CATEGORY = "USE_MENU_CATEGORY",
  ADMIN_MENU = "ADMIN_MENU",

  MINER_UNIT_PRICE = "MINER_UNIT_PRICE",
  MINER_UNIT_USDT_PRICE = "MINER_UNIT_USDT_PRICE",
  MINER_UNIT_VND_PRICE = "MINER_UNIT_VND_PRICE",
  SELLER_COMMISSIONS_RATE = "SELLER_COMMISSIONS_RATE",
  MERCHANT_COMMISSIONS_RATE = "MERCHANT_COMMISSIONS_RATE",

  BANK_NAME = "BANK_NAME",
  ACCOUNT_NAME = "ACCOUNT_NAME",
  BANK_NUMBER = "BANK_NUMBER",

  WALLET_NAME = "WALLET_NAME",
  WALLET_ADDRESS = "WALLET_ADDRESS",
  CRYPTO_SCAN = "CRYPTO_SCAN",
  EXCHANGE_RATE = "EXCHANGE_RATE",
}

export const SETTING_DATA = [
  {
    slug: SettingGroupSlug.COMMON,
    name: "Common setting",
    desc: "Common setting here",
    icon: "FcSettings",
    readOnly: true,
    settings: [
      {
        type: SettingTypes.string,
        name: "Website Title",
        key: SettingKey.TITLE,
        value: `botanika.ai`,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.string,
        name: "Website Domain",
        key: SettingKey.WEBSITE_DOMAIN,
        value: `http://botanika.ai/`,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.string,
        name: "Logo url",
        key: SettingKey.LOGO_URL,
        value: `/images/logo.png`,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.boolean,
        name: "Maintenance",
        key: SettingKey.MAINTENANCE,
        value: false,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
    ],
  },
  {
    slug: SettingGroupSlug.BOTANIKA,
    name: "Botanika setting",
    desc: "Botanika setting here",
    icon: "FcSettings",
    readOnly: true,
    settings: [
      {
        type: SettingTypes.number,
        name: "Miner unit USDT price",
        key: SettingKey.MINER_UNIT_USDT_PRICE,
        value: 1600,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.number,
        name: "Miner unit VND price",
        key: SettingKey.MINER_UNIT_VND_PRICE,
        value: 42000000,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.number,
        name: "USDT to VND Exchange rate",
        key: SettingKey.EXCHANGE_RATE,
        value: 26250,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.number,
        name: "Seller commission rate",
        key: SettingKey.SELLER_COMMISSIONS_RATE,
        value: 30,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.number,
        name: "Merchant commission rate",
        key: SettingKey.MERCHANT_COMMISSIONS_RATE,
        value: 30,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.string,
        name: "Bank name",
        key: SettingKey.BANK_NAME,
        value: "Vietcombank",
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.string,
        name: "Account bank name",
        key: SettingKey.ACCOUNT_NAME,
        value: `SKY`,
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.string,
        name: "Bank number",
        key: SettingKey.BANK_NUMBER,
        value: "0422000535114",
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.string,
        name: "Wallet name",
        key: SettingKey.WALLET_NAME,
        value: "Tron Wallet Address for payment",
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.string,
        name: "Wallet address",
        key: SettingKey.WALLET_ADDRESS,
        value: "TEneoUNBQjkid8NajzCeiZLqraBxbDy7",
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
      {
        type: SettingTypes.string,
        name: "Crypto scan",
        key: SettingKey.CRYPTO_SCAN,
        value: "https://tronscan.org/#/",
        isActive: true,
        isPrivate: false,
        readOnly: false,
      },
    ],
  },
];
