export enum SettingGroupSlug {
  COMMON = "COMMON",
  BOTANIKA = "BOTANIKA",
}
export enum SettingKey {
  // Cấu hình chung
  TITLE = "TITLE",
  WEBSITE_DOMAIN = "WEBSITE_DOMAIN",
  API_DOMAIN = "API_DOMAIN",
  MEDIA_DOMAIN = "MEDIA_DOMAIN",
  LOGO_URL = "LOGO_URL",
  MAINTENANCE = "MAINTENANCE",

  // cấu hình website
  USE_MENU_CATEGORY = "USE_MENU_CATEGORY",
  ADMIN_MENU = "ADMIN_MENU",

  MINER_UNIT_PRICE = "MINER_UNIT_PRICE",
  MINER_UNIT_USDT_PRICE = "MINER_UNIT_USDT_PRICE",
  MINER_UNIT_VND_PRICE = "MINER_UNIT_VND_PRICE",
  SELLER_COMMISSIONS_RATE = "SELLER_COMMISSIONS_RATE",
  MERCHANT_COMMISSIONS_RATE = "MERCHANT_COMMISSIONS_RATE",

  BANK_NAME = "BANK_NAME",
  ACCOUNT_NAME = "ACCOUNT_NAME",
  BANK_NUMBER = "BANK_NUMBER",

  ETH_WALLET_NAME = "ETH_WALLET_NAME",
  ETH_WALLET_ADDRESS = "ETH_WALLET_ADDRESS",
  ETH_CRYPTO_SCAN = "ETH_CRYPTO_SCAN",

  SOL_WALLET_NAME = "SOL_WALLET_NAME",
  SOL_WALLET_ADDRESS = "SOL_WALLET_ADDRESS",
  SOL_CRYPTO_SCAN = "SOL_CRYPTO_SCAN",

  EXCHANGE_RATE = "EXCHANGE_RATE",
  TOTAL_EMISSION = "TOTAL_EMISSION",
  HALVING_INTERVAL_DAYS = "HALVING_INTERVAL_DAYS",
  TOTAL_HALVING_PERIODS = "TOTAL_HALVING_PERIODS",
}

// export const SETTING_DATA = [
//   {
//     slug: SettingGroupSlug.COMMON,
//     name: "Common setting",
//     desc: "Common setting here",
//     icon: "FcSettings",
//     readOnly: true,
//     settings: [
//       {
//         type: SettingTypes.string,
//         name: "Website Title",
//         key: SettingKey.TITLE,
//         value: `botanika.ai`,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "Website Domain",
//         key: SettingKey.WEBSITE_DOMAIN,
//         value: `http://botanika.ai/`,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "Logo url",
//         key: SettingKey.LOGO_URL,
//         value: `/images/logo.png`,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.boolean,
//         name: "Maintenance",
//         key: SettingKey.MAINTENANCE,
//         value: false,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//     ],
//   },
//   {
//     slug: SettingGroupSlug.BOTANIKA,
//     name: "Botanika setting",
//     desc: "Botanika setting here",
//     icon: "FcSettings",
//     readOnly: true,
//     settings: [
//       {
//         type: SettingTypes.number,
//         name: "Miner unit USDT price",
//         key: SettingKey.MINER_UNIT_USDT_PRICE,
//         value: 1600,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.number,
//         name: "Miner unit VND price",
//         key: SettingKey.MINER_UNIT_VND_PRICE,
//         value: 42000000,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.number,
//         name: "USDT to VND Exchange rate",
//         key: SettingKey.EXCHANGE_RATE,
//         value: 26250,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.number,
//         name: "Seller commission rate",
//         key: SettingKey.SELLER_COMMISSIONS_RATE,
//         value: 30,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.number,
//         name: "Merchant commission rate",
//         key: SettingKey.MERCHANT_COMMISSIONS_RATE,
//         value: 30,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "Bank name",
//         key: SettingKey.BANK_NAME,
//         value: "ShinhanBank",
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "Account bank name",
//         key: SettingKey.ACCOUNT_NAME,
//         value: `KIM MINSUNG`,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "Bank number",
//         key: SettingKey.BANK_NUMBER,
//         value: "700036712005",
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "ETH wallet name",
//         key: SettingKey.ETH_WALLET_NAME,
//         value: "ETH/BSC Wallet Address for payment",
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "ETH wallet address",
//         key: SettingKey.ETH_WALLET_ADDRESS,
//         value: "0xC4dbc6284735B7868394Ca9984C5BBDca7833216",
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "ETH crypto scan",
//         key: SettingKey.ETH_CRYPTO_SCAN,
//         value: "https://etherscan.io",
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "SOL wallet name",
//         key: SettingKey.SOL_WALLET_NAME,
//         value: "Solana wallet address for payment",
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "Solana wallet address",
//         key: SettingKey.SOL_WALLET_ADDRESS,
//         value: "CmvCbtJpoVEKTpyBShWvWZDjhKxXkj3XsYbGUZqSRzfx",
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.string,
//         name: "Solana crypto scan",
//         key: SettingKey.SOL_CRYPTO_SCAN,
//         value: "https://solscan.io",
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.number,
//         name: "Total emission",
//         key: SettingKey.TOTAL_EMISSION,
//         value: 50000000000,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.number,
//         name: "Halving interval days",
//         key: SettingKey.HALVING_INTERVAL_DAYS,
//         value: 730,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//       {
//         type: SettingTypes.number,
//         name: "Total halving periods",
//         key: SettingKey.TOTAL_HALVING_PERIODS,
//         value: 10,
//         isActive: true,
//         isPrivate: false,
//         readOnly: false,
//       },
//     ],
//   },
// ];
