export const ROLES = {
  ADMIN: "ADMIN",
  EDITOR: "EDITOR",
  MEMBER: "MEMBER",
  MERCHANT: "MERCHANT",
  SALES: "SALES",
  CUSTOMER: "CUSTOMER",
  ADMIN_EDITOR: ["ADMIN", "EDITOR"],
  ADMIN_MEMBER: ["ADMIN", "MEMBER"],
  ADMIN_MEMBER_EDITOR: ["ADMIN", "EDITOR", "MEMBER"],
  ADMIN_EDITOR_CUSTOMER: ["ADMIN", "EDITOR", "CUSTOMER", "MERCHANT", "SALES"],
  ADMIN_MEMBER_CUSTOMER: ["ADMIN", "MEMBER", "CUSTOMER", "MERCHANT", "SALES"],
};
