name: Build PROD
on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APPNAME }}:prod

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Install SSH Client
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ENGLISH_CLASS_SSH_PRIVATE_KEY }}" > ~/.ssh/english-class.pem
          chmod 400 ~/.ssh/english-class.pem
          ssh-keyscan -H ${{ secrets.ENGLISH_CLASS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/english-class.pem \
            ${{ secrets.ENGLISH_CLASS_SSH_USERNAME }}@${{ secrets.ENGLISH_CLASS_IP }} '
              set -e
              # Tạo thư mục với quyền root (nếu chưa có)
              sudo mkdir -p /home/www/english-class
              sudo chown $USER:$USER /home/www/english-class
              cd /home/www/english-class

              # Xóa container và image cũ
              docker rm -f english-class-core || true
              docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APPNAME }}:prod || true

              # Dùng docker compose v2 nếu có, nếu không thì dùng docker-compose legacy
              (docker compose pull || docker-compose pull)
              (docker compose up -d || docker-compose up -d)
            '

